# Generated by Django 5.0.6 on 2024-06-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Module', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailybonus',
            old_name='is_active',
            new_name='is_done',
        ),
    ]
