# Generated by Django 5.0.6 on 2024-06-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Module', '0003_rename_is_active_dailybonus_is_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailybonus',
            old_name='is_done',
            new_name='is_active',
        ),
    ]
