# Generated by Django 5.0.6 on 2024-06-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Module', '0004_rename_is_done_dailybonus_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailybonus',
            name='deactivate_date',
        ),
    ]
