# Generated by Django 5.0.6 on 2024-06-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Module', '0005_remove_dailybonus_deactivate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybonus',
            name='deactivate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
