# Generated by Django 5.0.6 on 2024-06-20 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Module', '0007_alter_dailybonus_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailybonus',
            name='user',
        ),
        migrations.AddField(
            model_name='dailybonus',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
