# Generated by Django 5.0.6 on 2024-06-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Module', '0008_remove_dailybonus_user_dailybonus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='is_pined',
            field=models.BooleanField(default=False),
        ),
    ]
