# Generated by Django 5.0.6 on 2024-06-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Module', '0009_notifications_is_pined'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybonus',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailybonus',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
