# Generated by Django 5.0.6 on 2024-06-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Module', '0010_dailybonus_end_time_dailybonus_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybonus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
