# Generated by Django 5.0.6 on 2024-06-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Module', '0011_alter_dailybonus_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailybonus',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='dailybonus',
            name='start_time',
        ),
    ]
