# Generated by Django 5.0.6 on 2024-07-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Module', '0012_remove_dailybonus_end_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
