# Generated by Django 4.2 on 2024-07-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Module', '0013_delete_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfing',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
    ]
