# Generated by Django 4.2 on 2024-08-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Module', '0016_alter_tasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfing',
            name='app_version',
            field=models.IntegerField(default=1),
        ),
    ]
