# Generated by Django 4.2 on 2024-09-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Module', '0019_alter_adminalert_errortext_chatbot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chatbot',
        ),
    ]
