# Generated by Django 4.2 on 2024-09-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Module', '0020_delete_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfing',
            name='app_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
