# Generated by Django 4.2 on 2024-07-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moribit_Module', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferralSettings',
            new_name='ReferralGift',
        ),
    ]
