# Generated by Django 4.2 on 2024-07-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moribit_Module', '0004_alter_user_is_active_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_activity',
        ),
    ]
