# Generated by Django 4.2 on 2024-07-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moribit_Module', '0006_alter_giftcode_gift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosentforcheck',
            name='gift_coin_amount',
        ),
    ]
