# Generated by Django 4.2 on 2024-07-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moribit_Module', '0007_remove_videosentforcheck_gift_coin_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGiftCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_amount', models.IntegerField(default=100)),
            ],
        ),
    ]
