# Generated by Django 4.2 on 2024-07-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moribit_Module', '0008_videogiftcoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogiftcoin',
            name='coin_amount',
            field=models.BigIntegerField(default=100),
        ),
    ]
