# Generated by Django 4.2 on 2024-07-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moribit_Module', '0009_alter_videogiftcoin_coin_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemedcode',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
