# Generated by Django 4.2 on 2024-07-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moribit_Module', '0011_moriaiemailscode_delete_redeemedcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moriaiemailscode',
        ),
    ]
