# Generated by Django 4.2 on 2024-07-25 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Moribit_Module', '0013_moriaigiftcoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralgift',
            name='referral_coin_amount',
            field=models.BigIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='ads',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Dailybnonuseuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift', models.BigIntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
