# Generated by Django 4.2 on 2024-07-25 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moribit_Module', '0014_alter_referralgift_referral_coin_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybnonuseuser',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name='dailybnonuseuser',
            name='user',
        ),
        migrations.AddField(
            model_name='dailybnonuseuser',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
