# Generated by Django 4.2 on 2024-07-25 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moribit_Module', '0015_alter_dailybnonuseuser_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybnonuseuser',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
