# Generated by Django 4.2 on 2024-07-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moribit_Module', '0016_alter_dailybnonuseuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybnonuseuser',
            name='date_time',
            field=models.DateField(),
        ),
    ]
