# Generated by Django 4.2 on 2024-07-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moribit_Module', '0018_remove_dailybnonuseuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybnonuseuser',
            name='date_time',
            field=models.DateField(null=True),
        ),
    ]
