# Generated by Django 4.2 on 2024-07-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moribit_Module', '0019_alter_dailybnonuseuser_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybnonuseuser',
            name='days',
            field=models.IntegerField(default=1),
        ),
    ]
