# Generated by Django 4.2 on 2024-08-01 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Moribit_Module', '0020_dailybnonuseuser_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videosentforcheck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Dailybnonuseuser',
        ),
    ]
