# Generated by Django 4.2 on 2024-08-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moribit_Module', '0021_alter_user_level_alter_user_referred_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='webappusercode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('gift', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
