# Generated by Django 4.2 on 2024-08-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moribit_Module', '0022_webappusercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coin',
            field=models.BigIntegerField(default=100000),
        ),
    ]
