# Generated by Django 4.2 on 2024-08-31 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Moribit_Module', '0023_alter_user_coin'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jack_pot', models.IntegerField(default=20)),
                ('turbo', models.IntegerField(default=3)),
                ('energy', models.IntegerField(default=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
